plugins { id 'com.android.application' }

android {
    namespace 'com.solumetals.formatoscomerciales'
    compileSdk 35
    defaultConfig {
        applicationId 'com.solumetals.formatoscomerciales'
        minSdk 24
        targetSdk 35
        versionCode 7
        versionName '2.3.0'
    }
}

dependencies { implementation 'androidx.core:core:1.15.0' }
